#ifndef CONFIG_H
#define CONFIG_H

#define ENABLE_RL02
#define ENABLE_KW11
//#define ENABLE_KW11_DEBUG

//#define CPU_SP_ODD_VALUE_DETECT

#define ENABLE_RK05

#define CPU_ILLEGAL_INSTRUCTION_INFO

#endif